server:
  port: 8081
  servlet.context-path: /
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password: 123456@A
  jpa:
    show-sql: true
  kafka:
    bootstrapServers: ${kafka_server_url:localhost:9092}
    topics:
      ping: ping-topic
